services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    depends_on:
      - browserless
    environment:
      - BROWSERLESS_URL=http://browserless:5001
  browserless:
    image: browserless/chrome:latest
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      